### ISSUE TITLE
TImer opens up unexpectedly on long-finished comments

### ISSUE THREAD

**Issue by CKMacLeod** [ronalfy/simple-comment-editing#12]
Lately I've been encountering an issue I've never noticed before the recent updates, though it resembles a very minor one I had previously noticed, and may be the same as or related to one mentioned on the Wordpress.org support thread. 

In short, when returning to a comment thread where I have previously left and possibly edited a comment or more than one comment, I will find an old comment counting down from a very high number, far exceeding the normal 5-minute limit. 

For example:

![odd sce result 2](https://cloud.githubusercontent.com/assets/6822649/10235014/70764424-684d-11e5-9934-cd16afa0e9b5.png)
Also:

![odd sce result](https://cloud.githubusercontent.com/assets/6822649/10235015/70770b02-684d-11e5-83cf-954ce724e9c7.png)

353 minutes to edit!

You seemed at WP.org to suggest that this problem had something do with caching. I cleared both browser and site caches, and it DID go away (since last night), but I'm wondering why it's only appearing lately: I've bee using SCE for years, and have never seen anything like it. The very minor problem that it resembles, that I have NOT recently seen, was that I would occasionally return to a thread and find the countdown suspended. It would then re-start and accelerate to the end.

I don't see this matter as one of great urgency, but I do think it would be worth solving.

**Comment by ronalfy** [comment]
It may be related that user accounts are being tied to end too late. Let me
test this more this weekend.

**Comment by CKMacLeod** [comment]
Wondering if you've made any progress, and thought I'd note that I've now gotten one user inquiry - a user wondering if I had raised the default edit time from 5 minutes to 60 minutes: So it's not a rarity. An contemplating switching to an earlier version, at some loss to the new filter-based functionality, but will probably hold out a while longer.

**Comment by ronalfy** [comment]
I've been unable to duplicate either error where a user sees an undefined or somebody sees a large countdown.

**Comment by CKMacLeod** [comment]
Hmmm... I'm able to re-produce it on threads at the site where it's installed. And was able to get this:

![new_sce_bad_comment](https://cloud.githubusercontent.com/assets/6822649/10298034/94edac86-6b8e-11e5-9f12-5aebdedba828.png)

A new record - and, yes, the comment is really editable, and a browser cache flush DOES eliminate it.

Not sure EXACTLY how or what was critical, but, what I just did was 1) leave several new comments, 2) also open another browser and add a couple of comments under a different name, 3) Refresh along the way, separately, without adding any comments, 4) return to the thread, scanning the comments, 

The comment showing the opened-up timer is a completely different old comment, not one of the new experimental ones. (I happened to be testing SCE 1.6.5 at the time, coincidentally enough.) It's the only one of 75 comments on the thread that opened up for editing - http://ordinary-gentlemen.com/developing/2015/09/cookie-assortment/#comment-402

There are a lot of customizations affecting commenting on this thread - it's something I've been working on for a long time - plus the theme on which the current child-theme is based is a little unusual - but I have no idea whether one plug-in or function is interacting with SCE, and, as I said, I never noticed this exact behavior previously to the recent updates. 

Feel free to add as many comments as you like, if you want to try for yourself.

**Comment by ronalfy** [comment]
Ok, I'll have some time this week to track this some more.

**Comment by ronalfy** [comment]
@CKMacLeod I was finally able to duplicate this.

I just pushed 1.8.3, which should fix this issue.

https://wordpress.org/plugins/simple-comment-editing/

**Comment by CKMacLeod** [comment]
Great. I've updated, and I'll let you know if the funk returns. 

I've checked what you did in the index.php to fix "rogue editing times" (good definition!). I'm curious if anything else had to be altered, and if the code that was fixed had been changed from earlier versions of the plug-in (i.e., why this problem showed up now).

Thanks!

**Comment by ronalfy** [comment]
I recently added some code for logged in users. Looks like the bugs were
always there, just the logged in issues allowed them to surface.

**Comment by ronalfy** [comment]
I'm going to close this for now, but please re-open if the issue still persists. I think I got it licked though now from two angles: https://github.com/ronalfy/simple-comment-editing/commit/8764916135e9ecb82693ba9be4bebf7898341ba3 and https://github.com/ronalfy/simple-comment-editing/commit/8de1ebf50000a950bf6040e0e55b4d0117d9174f
