### ISSUE TITLE
Why not putting all js files in footer

### ISSUE THREAD

**Issue by isaumya** [ronalfy/simple-comment-editing#13]
I was looking into your plugin code in github and saw that you dont add all of your js files into footer. Some of them has true set while for others its get added into the head. Any special reason for that?

**Comment by ronalfy** [comment]
Should be fixed with this: https://github.com/ronalfy/simple-comment-editing/commit/8b57f92ec7417e1f0d2c6f14a3fedf2910c66b50

It'll go out on my next update.

**Comment by isaumya** [comment]
Yes, it would be fixed by that. But I also have another tips for this plugin. I saw that your plugin loads all js files as unminified. This is bad man, as unminified files will take more space (yah I knew a few kb maybe, but it still matters) and also if someone is not using a minification plugin on their site they cannot minify it. 

This is what I do on my plugins that I develop. In my asset folder I first write the js and save it as normal js file then using sublime text minification package (you can use anything you like) I create the minified version of the same file as .min.js and then call the min js in the plugin script but keep the non minified js file still in my asset folder - so that if any nerd wanna tweak the code they can do it easily and then again make a minified version of that to overwrite the existing. So, everyone is happy. :smile_cat: 

![2015-11-04_16-02-29](https://cloud.githubusercontent.com/assets/2124755/10935682/a4ed5154-830d-11e5-9f58-ad297a37ab01.jpg)

I think you can also follow the same approach in your plugin.

**Comment by ronalfy** [comment]
I do serve my main plugin file as minified, but the wp hooks plugin is so
small, I chose not to minify that one.

**Comment by isaumya** [comment]
well small files can still me smaller :) Just a thought :)

**Comment by ronalfy** [comment]
Leave this ticket open and I'll push out an update this week.

**Comment by ronalfy** [comment]
Both of those should be fixed with SCE 1.9.1
