### ISSUE TITLE
Loading image doesn't show up

### ISSUE THREAD

**Issue by isaumya** [ronalfy/simple-comment-editing#14]
Though there is a loading image call but still it doesnt show up any loading image in my comment form. You can check any posts at https://www.isaumya.com/blog/ and try posting a test comment you will see.

I've also added my custom loading image - 

```
add_filter( 'sce_loading_img', 'edit_sce_loading_img' );
function edit_sce_loading_img( $default_url ) {
    return get_stylesheet_directory_uri() . '/assets/images/spinner.gif';
}
```

But still doesn't show up. Do you know why?

**Comment by ronalfy** [comment]
I left a test comment and was able to see your new fancy loading icon.

**Comment by ronalfy** [comment]
![sce-loading](https://cloud.githubusercontent.com/assets/636521/10928227/5638b7de-826c-11e5-9634-d2a6270d59a3.jpg)

**Comment by isaumya** [comment]
Does this loading image shows when someone update the comment? Or when the script is loading? I'm confused I guess.

**Comment by ronalfy** [comment]
When someone has saved their comment.

**Comment by isaumya** [comment]
Ok. I got it:)
