### ISSUE TITLE
Registered user able to edit all the time

### ISSUE THREAD

**Issue by cf-moriarty** [ronalfy/simple-comment-editing#16]
Hello there,

I'm looking for a filter, a solution which allow registered users able to edit their own posts all the time, not with limited time (if so, what is the difference between them and anonymous?)

I like this plugin, simple and powerful. Just like my nickname.

Regards,
Napoleon of Crime.

**Comment by ronalfy** [comment]
Napoleon,

My apologies, but this plugin was specifically designed/coded to allow anonymous users the ability to comment.

**Comment by cf-moriarty** [comment]
What a pity! My site are not allow anonymous comment. Registered only...

**Comment by nguyenlamlll** [comment]
Just a question, why can't we allow users (anonymous or registered) to edit freely (with no timer)?
