### ISSUE TITLE
Postmatic does not wait for comment edits 

### ISSUE THREAD

**Issue by newlocalmedia** [ronalfy/simple-comment-editing#18]
SCE does not prevent Postmatic -- and Postmatic does not refrain -- from emailing new comments to subscribers while they can still be edited.

**Comment by ronalfy** [comment]
I appreciate you bringing up this issue.

I can't think of a good solution as there is no feedback loop when the comment editing time has elapsed. We could use cron, but you know how unreliable that is.

I'll get with Jason and see if there is a solution, but at this point, it doesn't seem likely.
