### ISSUE TITLE
BUG: Comment get deleted, also when i press cancel.

### ISSUE THREAD

**Issue by Overpowered** [ronalfy/simple-comment-editing#23]
Hi,

I think I found a little bug. If I press the "delete"-button, inside the editing mode, and then "cancel" instead of "ok", the comment will be also deleted ;(.

**Comment by Lokoyote** [comment]
Hi,
I have the bug too...

**Comment by ronalfy** [comment]
Sorry about the bug. I’m on vacation without my work computer until the 11th. I’ll try to fix the bug then.

**Comment by ronalfy** [comment]
@Overpowered @Lokoyote 

This bug should be resolved in 2.1.9. Very sorry I didn't catch that bug.

**Comment by Overpowered** [comment]
@ronalfy 
Nobody is perfect ;) - looking forward to the update. Thx.

**Comment by Lokoyote** [comment]
@ronalfy
Everything works perfectly, don't worry for that bug. Thanks a lot for your support!

**Comment by ronalfy** [comment]
Thanks yall. If you have time, can you please rate the plugin? Thanks!
