### ISSUE TITLE
Simple Comment Editing stopped working with most recently update

### ISSUE THREAD

**Issue by WyattHoutz** [ronalfy/simple-comment-editing#26]
Fatal error: Can't use function return value in write context in /home1/whoutz/public_html/wp-content/plugins/simple-comment-editing/simple-comment-editing.php on line 798

**Comment by ronalfy** [comment]
@WyattHoutz this is a PHP bug if you're running 5.3 or lower. I'll have it fixed in the next version, but I encourage you to run a higher PHP version.

**Comment by ronalfy** [comment]
Resolved after this commit: https://github.com/ronalfy/simple-comment-editing/commit/30a08a930f1e39465139f3a691fecc3457486730
