### ISSUE TITLE
Multisite alternative scenario

### ISSUE THREAD

**Issue by remkus** [ronalfy/simple-comment-editing#30]
In class-sce-admin.php on L40 you do a check to see whether the plugin is in a multi-site, but this will also default to TRUE if we're on a subsite in a multi-site. This is probably too broad of a check. Particularly when you _only_ want to active the plugin on one or more selected subsites in a network.

**Comment by ronalfy** [comment]
@remkus welcome to my neck of the woods! I'll investigate the code and use-case and get back to you.
