### ISSUE TITLE
Refactor for cached posts

### ISSUE THREAD

**Issue by daankortenbach** [ronalfy/simple-comment-editing#4]
Referring to http://wordpress.org/support/topic/can-this-be-used-on-cached-pages.

Hit me and/or @ryanhellyer up if you need assistance.

**Comment by ronalfy** [comment]
Dan, please re-open if you find anything new to add here.

Epoch just released their front-end comment area replacement, and it works very well with SCE. I'm assuming with the combination of both of these, the caching issues should go away.

https://wordpress.org/plugins/epoch/

**Comment by daankortenbach** [comment]
No need to reopen. If I remember correctly we implemented a shorter cookie timeout and per user caching. Thanks for the follow up!
