### ISSUE TITLE
Sprintf error, line 153 in index.php

### ISSUE THREAD

**Issue by bernie-simon** [ronalfy/simple-comment-editing#7]
It looks like the code which embeds $raw_content into $textarea_content at line 135 isn't checking for percent signs. If one is present, when the $textarea_content is used as a print format at line 153, it will throw an error and say sprintf has too few arguments.

**Comment by ronalfy** [comment]
Thank you. This is just default behavior? Just confirming so I can test.

**Comment by bernie-simon** [comment]
If $raw_content contains a percent sign, it will throw the error.

**Comment by ronalfy** [comment]
!!! Wow. Okay, I understand now. I'll try to get this patched as soon as possible.

**Comment by ronalfy** [comment]
Thanks again. I fixed it in https://github.com/ronalfy/simple-comment-editing/commit/46b0188faa1497c87b10a64feea6bcba7399a99f but I don't have SVN access at the moment, so I'll push out an update on .org when I get home in a few hours.
